const observations={A1:{location:'North section',status:'healthy',issue:'No significant symptoms',symptoms:'Healthy green foliage; no clear lesions observed.',why:'This scanned plant appears healthy, with even leaf color and no notable damage.'},A2:{location:'East section',status:'attention',issue:'Possible early leaf spot',symptoms:'Small brown spots and slight leaf yellowing.',why:'Early symptoms are visible, but the pattern needs monitoring and confirmation.'},B1:{location:'Center section',status:'attention',issue:'Possible fungal-like symptoms',symptoms:'Brown lesions, yellowing around lower leaves.',why:'Symptoms are consistent with the recurring pattern seen in other scanned points.'},C1:{location:'South section',status:'urgent',issue:'Possible early blight · moderate confidence',symptoms:'More pronounced brown lesions, leaf yellowing, and damaged lower foliage.',why:'This area shows more severe leaf damage than other scanned locations, making it the highest priority.'},C2:{location:'South-east section',status:'attention',issue:'Possible fungal-like symptoms',symptoms:'Moderate spotting with leaf yellowing.',why:'Similar symptoms occur in nearby observations, suggesting a pattern among scanned areas.'}};
const detail=document.getElementById('detailDialog');
function showDetail(id){const o=observations[id];document.getElementById('detailId').textContent=id;document.getElementById('detailLocation').textContent=o.location.toUpperCase();document.getElementById('detailSymptoms').textContent=o.symptoms;document.getElementById('detailIssue').textContent=o.issue;document.getElementById('detailWhy').textContent=o.why;document.getElementById('detailDot').style.background=o.status==='urgent'?'#d65643':o.status==='attention'?'#efa92c':'#54a874';detail.showModal()}
document.querySelectorAll('.pin,.arrow-btn').forEach(x=>x.addEventListener('click',()=>showDetail(x.dataset.id)));
document.getElementById('closeDetail').onclick=()=>detail.close();
const dialog=document.getElementById('observationDialog');document.getElementById('scanBtn').onclick=()=>dialog.showModal();document.getElementById('addObsMap').onclick=()=>dialog.showModal();document.getElementById('rescanBtn').onclick=()=>{document.getElementById('scanBtn').click();};
document.getElementById('imageInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const p=document.getElementById('preview');p.src=URL.createObjectURL(f);p.style.display='block';document.getElementById('uploadHint').style.display='none'};
document.getElementById('saveObs').addEventListener('click',e=>{e.preventDefault();dialog.close();runAnalysis();});
function runAnalysis(){const toast=document.getElementById('scanToast'),stage=document.getElementById('scanStage'),steps=[['Images received',0],['Individual observations analyzed',1],['Symptoms compared',2],['Field patterns identified',3],['Weather checked',4],['Action plan generated',5]];toast.classList.add('show');steps.forEach(([text,i])=>setTimeout(()=>{stage.textContent=text;document.querySelectorAll('.steps span')[i].className='done';document.querySelectorAll('.steps span')[i].textContent='✓ '+text},i*650));setTimeout(()=>{toast.classList.remove('show');window.scrollTo({top:document.querySelector('.overview-grid').offsetTop-60,behavior:'smooth'})},4400)}
function setHealthy(){document.getElementById('score').textContent='88';document.getElementById('status').textContent='Healthy';document.getElementById('healthText').textContent='Your sampled areas look stable.';document.getElementById('meterFill').style.cssText='width:88%;background:#54a874';document.getElementById('lowCount').textContent='4';document.getElementById('attentionCount').textContent='1';document.getElementById('highCount').textContent='0';document.querySelector('.priority-card h3').innerHTML='Continue regular monitoring <span style="color:#43805a;background:#e7f4e9">Low concern</span>';document.getElementById('priorityWhy').textContent='Only one sampled point shows minor stress. There is no clear recurring damage pattern.';document.querySelector('.pattern-card h3').innerHTML='Minor stress signals <b>1 / 5</b>';document.querySelector('.pattern-card p').textContent='Most of the scanned observations look healthy. Continue checking the field routinely.';document.querySelectorAll('.pin').forEach((p,i)=>{p.className='pin '+(i===1?'attention':'healthy')});window.scrollTo({top:document.querySelector('.overview-grid').offsetTop-60,behavior:'smooth'})}
document.getElementById('healthyBtn').onclick=setHealthy;document.getElementById('demoBtn').onclick=()=>{location.reload()};
const answer=document.getElementById('copilotAnswer');function respond(q){q=q.toLowerCase();if(q.includes('first')||q.includes('area'))answer.textContent='Start with the South section. It has the most severe symptoms among the sampled points. Then check the nearby Center and East areas.';else if(q.includes('spread'))answer.textContent='Similar spotting and yellowing appear in 3 of 5 scanned points. That suggests a pattern among sampled areas, so inspect nearby plants for confirmation.';else if(q.includes('tomorrow')||q.includes('check'))answer.textContent='Tomorrow morning, inspect lower leaves in the South and Center sections. With rain expected tonight, look for any new moisture-related spotting.';else answer.textContent='Based on this scan, the South section is the priority. The assessment is based on sampled points and should be confirmed with a close field inspection.'}
document.querySelectorAll('.suggestions button').forEach(b=>b.onclick=()=>respond(b.textContent));document.getElementById('copilotForm').onsubmit=e=>{e.preventDefault();const v=document.getElementById('copilotInput').value;if(v){respond(v);document.getElementById('copilotInput').value=''}};
